apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cultivation-ingress
  namespace: cultivation-game
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/websocket-services: gateway
spec:
  ingressClassName: nginx
  rules:
    - host: cultivation-game.local
      http:
        paths:
          - path: /ws(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: gateway
                port:
                  number: 8080
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: gateway
                port:
                  number: 8081
          - path: /?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend
                port:
                  number: 80
