apiVersion: v1
kind: Service
metadata:
  name: ranking
  namespace: cultivation-game
  labels:
    app: ranking
spec:
  type: ClusterIP
  selector:
    app: ranking
  ports:
    - name: http
      port: 8089
      targetPort: 8089
