apiVersion: v1
kind: Service
metadata:
  name: trade
  namespace: cultivation-game
  labels:
    app: trade
spec:
  type: ClusterIP
  selector:
    app: trade
  ports:
    - name: http
      port: 8088
      targetPort: 8088
