// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/game_message.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GameMessage - 统一消息信封
type GameMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         uint32                 `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`         // 消息类型ID
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`                          // 序列号(保证顺序)
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`              // 时间戳
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                   // 业务数据(protobuf编码)
	Status        uint32                 `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`                    // 状态码(0=成功)
	ErrorMsg      string                 `protobuf:"bytes,6,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"` // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameMessage) Reset() {
	*x = GameMessage{}
	mi := &file_proto_game_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameMessage) ProtoMessage() {}

func (x *GameMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameMessage.ProtoReflect.Descriptor instead.
func (*GameMessage) Descriptor() ([]byte, []int) {
	return file_proto_game_message_proto_rawDescGZIP(), []int{0}
}

func (x *GameMessage) GetMsgId() uint32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *GameMessage) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *GameMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GameMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GameMessage) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GameMessage) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

// 修炼消息
type CultivateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TechniqueId   uint32                 `protobuf:"varint,1,opt,name=technique_id,json=techniqueId,proto3" json:"technique_id,omitempty"`
	Duration      uint32                 `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CultivateReq) Reset() {
	*x = CultivateReq{}
	mi := &file_proto_game_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CultivateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CultivateReq) ProtoMessage() {}

func (x *CultivateReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CultivateReq.ProtoReflect.Descriptor instead.
func (*CultivateReq) Descriptor() ([]byte, []int) {
	return file_proto_game_message_proto_rawDescGZIP(), []int{1}
}

func (x *CultivateReq) GetTechniqueId() uint32 {
	if x != nil {
		return x.TechniqueId
	}
	return 0
}

func (x *CultivateReq) GetDuration() uint32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type CultivateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpGained     uint64                 `protobuf:"varint,1,opt,name=exp_gained,json=expGained,proto3" json:"exp_gained,omitempty"`
	NewRealm      uint32                 `protobuf:"varint,2,opt,name=new_realm,json=newRealm,proto3" json:"new_realm,omitempty"`
	Breakthrough  bool                   `protobuf:"varint,3,opt,name=breakthrough,proto3" json:"breakthrough,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CultivateResp) Reset() {
	*x = CultivateResp{}
	mi := &file_proto_game_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CultivateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CultivateResp) ProtoMessage() {}

func (x *CultivateResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CultivateResp.ProtoReflect.Descriptor instead.
func (*CultivateResp) Descriptor() ([]byte, []int) {
	return file_proto_game_message_proto_rawDescGZIP(), []int{2}
}

func (x *CultivateResp) GetExpGained() uint64 {
	if x != nil {
		return x.ExpGained
	}
	return 0
}

func (x *CultivateResp) GetNewRealm() uint32 {
	if x != nil {
		return x.NewRealm
	}
	return 0
}

func (x *CultivateResp) GetBreakthrough() bool {
	if x != nil {
		return x.Breakthrough
	}
	return false
}

// 战斗消息
type CombatAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillId       uint32                 `protobuf:"varint,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	TargetId      uint64                 `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombatAction) Reset() {
	*x = CombatAction{}
	mi := &file_proto_game_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatAction) ProtoMessage() {}

func (x *CombatAction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatAction.ProtoReflect.Descriptor instead.
func (*CombatAction) Descriptor() ([]byte, []int) {
	return file_proto_game_message_proto_rawDescGZIP(), []int{3}
}

func (x *CombatAction) GetSkillId() uint32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *CombatAction) GetTargetId() uint64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

type CombatRound struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Damage        int64                  `protobuf:"varint,2,opt,name=damage,proto3" json:"damage,omitempty"`
	IsCritical    bool                   `protobuf:"varint,3,opt,name=is_critical,json=isCritical,proto3" json:"is_critical,omitempty"`
	AttackerId    uint64                 `protobuf:"varint,4,opt,name=attacker_id,json=attackerId,proto3" json:"attacker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombatRound) Reset() {
	*x = CombatRound{}
	mi := &file_proto_game_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatRound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatRound) ProtoMessage() {}

func (x *CombatRound) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatRound.ProtoReflect.Descriptor instead.
func (*CombatRound) Descriptor() ([]byte, []int) {
	return file_proto_game_message_proto_rawDescGZIP(), []int{4}
}

func (x *CombatRound) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CombatRound) GetDamage() int64 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *CombatRound) GetIsCritical() bool {
	if x != nil {
		return x.IsCritical
	}
	return false
}

func (x *CombatRound) GetAttackerId() uint64 {
	if x != nil {
		return x.AttackerId
	}
	return 0
}

// 玩家基础信息
type PlayerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	RealmId       uint32                 `protobuf:"varint,3,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	RealmLevel    uint32                 `protobuf:"varint,4,opt,name=realm_level,json=realmLevel,proto3" json:"realm_level,omitempty"`
	Exp           uint64                 `protobuf:"varint,5,opt,name=exp,proto3" json:"exp,omitempty"`
	SpiritRoot    string                 `protobuf:"bytes,6,opt,name=spirit_root,json=spiritRoot,proto3" json:"spirit_root,omitempty"` // 灵根属性
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInfo) Reset() {
	*x = PlayerInfo{}
	mi := &file_proto_game_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo) ProtoMessage() {}

func (x *PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfo.ProtoReflect.Descriptor instead.
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return file_proto_game_message_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PlayerInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *PlayerInfo) GetRealmId() uint32 {
	if x != nil {
		return x.RealmId
	}
	return 0
}

func (x *PlayerInfo) GetRealmLevel() uint32 {
	if x != nil {
		return x.RealmLevel
	}
	return 0
}

func (x *PlayerInfo) GetExp() uint64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *PlayerInfo) GetSpiritRoot() string {
	if x != nil {
		return x.SpiritRoot
	}
	return ""
}

var File_proto_game_message_proto protoreflect.FileDescriptor

const file_proto_game_message_proto_rawDesc = "" +
	"\n" +
	"\x18proto/game_message.proto\x12\x04game\"\xa3\x01\n" +
	"\vGameMessage\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\rR\x05msgId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x16\n" +
	"\x06status\x18\x05 \x01(\rR\x06status\x12\x1b\n" +
	"\terror_msg\x18\x06 \x01(\tR\berrorMsg\"M\n" +
	"\fCultivateReq\x12!\n" +
	"\ftechnique_id\x18\x01 \x01(\rR\vtechniqueId\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\rR\bduration\"o\n" +
	"\rCultivateResp\x12\x1d\n" +
	"\n" +
	"exp_gained\x18\x01 \x01(\x04R\texpGained\x12\x1b\n" +
	"\tnew_realm\x18\x02 \x01(\rR\bnewRealm\x12\"\n" +
	"\fbreakthrough\x18\x03 \x01(\bR\fbreakthrough\"F\n" +
	"\fCombatAction\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\rR\askillId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x04R\btargetId\"\x89\x01\n" +
	"\vCombatRound\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x16\n" +
	"\x06damage\x18\x02 \x01(\x03R\x06damage\x12\x1f\n" +
	"\vis_critical\x18\x03 \x01(\bR\n" +
	"isCritical\x12\x1f\n" +
	"\vattacker_id\x18\x04 \x01(\x04R\n" +
	"attackerId\"\xa7\x01\n" +
	"\n" +
	"PlayerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x19\n" +
	"\brealm_id\x18\x03 \x01(\rR\arealmId\x12\x1f\n" +
	"\vrealm_level\x18\x04 \x01(\rR\n" +
	"realmLevel\x12\x10\n" +
	"\x03exp\x18\x05 \x01(\x04R\x03exp\x12\x1f\n" +
	"\vspirit_root\x18\x06 \x01(\tR\n" +
	"spiritRootB%Z#cultivation-game/shared/proto;protob\x06proto3"

var (
	file_proto_game_message_proto_rawDescOnce sync.Once
	file_proto_game_message_proto_rawDescData []byte
)

func file_proto_game_message_proto_rawDescGZIP() []byte {
	file_proto_game_message_proto_rawDescOnce.Do(func() {
		file_proto_game_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_game_message_proto_rawDesc), len(file_proto_game_message_proto_rawDesc)))
	})
	return file_proto_game_message_proto_rawDescData
}

var file_proto_game_message_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_game_message_proto_goTypes = []any{
	(*GameMessage)(nil),   // 0: game.GameMessage
	(*CultivateReq)(nil),  // 1: game.CultivateReq
	(*CultivateResp)(nil), // 2: game.CultivateResp
	(*CombatAction)(nil),  // 3: game.CombatAction
	(*CombatRound)(nil),   // 4: game.CombatRound
	(*PlayerInfo)(nil),    // 5: game.PlayerInfo
}
var file_proto_game_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_game_message_proto_init() }
func file_proto_game_message_proto_init() {
	if File_proto_game_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_game_message_proto_rawDesc), len(file_proto_game_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_game_message_proto_goTypes,
		DependencyIndexes: file_proto_game_message_proto_depIdxs,
		MessageInfos:      file_proto_game_message_proto_msgTypes,
	}.Build()
	File_proto_game_message_proto = out.File
	file_proto_game_message_proto_goTypes = nil
	file_proto_game_message_proto_depIdxs = nil
}
