// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/ranking.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RankingService_GetRanking_FullMethodName    = "/ranking.RankingService/GetRanking"
	RankingService_GetPlayerRank_FullMethodName = "/ranking.RankingService/GetPlayerRank"
	RankingService_GetTopPlayers_FullMethodName = "/ranking.RankingService/GetTopPlayers"
)

// RankingServiceClient is the client API for RankingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RankingService 排行榜 gRPC 服务。
type RankingServiceClient interface {
	// GetRanking 获取排行榜（分页）。
	GetRanking(ctx context.Context, in *GetRankingRequest, opts ...grpc.CallOption) (*GetRankingResponse, error)
	// GetPlayerRank 查询指定玩家的排名及周围邻居。
	GetPlayerRank(ctx context.Context, in *GetPlayerRankRequest, opts ...grpc.CallOption) (*GetPlayerRankResponse, error)
	// GetTopPlayers 获取榜单前 N 名。
	GetTopPlayers(ctx context.Context, in *GetTopPlayersRequest, opts ...grpc.CallOption) (*GetTopPlayersResponse, error)
}

type rankingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRankingServiceClient(cc grpc.ClientConnInterface) RankingServiceClient {
	return &rankingServiceClient{cc}
}

func (c *rankingServiceClient) GetRanking(ctx context.Context, in *GetRankingRequest, opts ...grpc.CallOption) (*GetRankingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRankingResponse)
	err := c.cc.Invoke(ctx, RankingService_GetRanking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankingServiceClient) GetPlayerRank(ctx context.Context, in *GetPlayerRankRequest, opts ...grpc.CallOption) (*GetPlayerRankResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlayerRankResponse)
	err := c.cc.Invoke(ctx, RankingService_GetPlayerRank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankingServiceClient) GetTopPlayers(ctx context.Context, in *GetTopPlayersRequest, opts ...grpc.CallOption) (*GetTopPlayersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopPlayersResponse)
	err := c.cc.Invoke(ctx, RankingService_GetTopPlayers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RankingServiceServer is the server API for RankingService service.
// All implementations must embed UnimplementedRankingServiceServer
// for forward compatibility.
//
// RankingService 排行榜 gRPC 服务。
type RankingServiceServer interface {
	// GetRanking 获取排行榜（分页）。
	GetRanking(context.Context, *GetRankingRequest) (*GetRankingResponse, error)
	// GetPlayerRank 查询指定玩家的排名及周围邻居。
	GetPlayerRank(context.Context, *GetPlayerRankRequest) (*GetPlayerRankResponse, error)
	// GetTopPlayers 获取榜单前 N 名。
	GetTopPlayers(context.Context, *GetTopPlayersRequest) (*GetTopPlayersResponse, error)
	mustEmbedUnimplementedRankingServiceServer()
}

// UnimplementedRankingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRankingServiceServer struct{}

func (UnimplementedRankingServiceServer) GetRanking(context.Context, *GetRankingRequest) (*GetRankingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRanking not implemented")
}
func (UnimplementedRankingServiceServer) GetPlayerRank(context.Context, *GetPlayerRankRequest) (*GetPlayerRankResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlayerRank not implemented")
}
func (UnimplementedRankingServiceServer) GetTopPlayers(context.Context, *GetTopPlayersRequest) (*GetTopPlayersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopPlayers not implemented")
}
func (UnimplementedRankingServiceServer) mustEmbedUnimplementedRankingServiceServer() {}
func (UnimplementedRankingServiceServer) testEmbeddedByValue()                        {}

// UnsafeRankingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RankingServiceServer will
// result in compilation errors.
type UnsafeRankingServiceServer interface {
	mustEmbedUnimplementedRankingServiceServer()
}

func RegisterRankingServiceServer(s grpc.ServiceRegistrar, srv RankingServiceServer) {
	// If the following call pancis, it indicates UnimplementedRankingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RankingService_ServiceDesc, srv)
}

func _RankingService_GetRanking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRankingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankingServiceServer).GetRanking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RankingService_GetRanking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankingServiceServer).GetRanking(ctx, req.(*GetRankingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RankingService_GetPlayerRank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerRankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankingServiceServer).GetPlayerRank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RankingService_GetPlayerRank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankingServiceServer).GetPlayerRank(ctx, req.(*GetPlayerRankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RankingService_GetTopPlayers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopPlayersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankingServiceServer).GetTopPlayers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RankingService_GetTopPlayers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankingServiceServer).GetTopPlayers(ctx, req.(*GetTopPlayersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RankingService_ServiceDesc is the grpc.ServiceDesc for RankingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RankingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ranking.RankingService",
	HandlerType: (*RankingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRanking",
			Handler:    _RankingService_GetRanking_Handler,
		},
		{
			MethodName: "GetPlayerRank",
			Handler:    _RankingService_GetPlayerRank_Handler,
		},
		{
			MethodName: "GetTopPlayers",
			Handler:    _RankingService_GetTopPlayers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/ranking.proto",
}
